name: /opt/homebrew/anaconda3/envs/projet-en-tal
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
      - accelerate==0.28.0
      - altair==5.3.0
      - annotated-types==0.7.0
      - blis==0.7.11
      - catalogue==2.0.10
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - cymem==2.0.8
      - datasets==2.18.0
      - dill==0.3.8
      - en-core-web-sm==3.7.1
      - evaluate==0.4.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.22.2
      - ipywidgets==8.1.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.10
      - langcodes==3.4.0
      - language-data==1.2.0
      - marisa-trie==1.1.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - preshed==3.0.9
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydeck==0.9.1
      - referencing==0.35.1
      - responses==0.18.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - sentencepiece==0.2.0
      - seqeval==1.2.2
      - smart-open==6.4.0
      - smmap==5.0.1
      - spacy==3.7.4
      - spacy-alignments==0.9.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-streamlit==1.0.6
      - spacy-transformers==1.3.5
      - spacy-wrap==1.4.5
      - srsly==2.4.8
      - streamlit==1.35.0
      - tenacity==8.3.0
      - thinc==8.2.3
      - toml==0.10.2
      - toolz==0.12.1
      - transformers==4.36.2
      - typer==0.9.4
      - wasabi==1.1.2
      - weasel==0.3.4
      - widgetsnbextension==4.0.10
      - xxhash==3.4.1
